# Generated by Django 3.0.4 on 2020-03-09 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='user_profile'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to=settings.AUTH_USER_MODEL, verbose_name='room')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_room', to='game_2.Room', verbose_name='user_room'),
        ),
    ]
