# Generated by Django 3.0.4 on 2020-03-15 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_2', '0003_auto_20200309_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='x_center',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='y_center',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='killer',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='killer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='x',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='y',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
