# Generated by Django 3.0.4 on 2020-03-15 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_2', '0005_auto_20200315_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_room', to='game_2.Room', verbose_name='user_room'),
        ),
    ]
