# Generated by Django 3.0.4 on 2020-03-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_2', '0007_userprofile_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
