# Generated by Django 2.2 on 2020-08-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_2', '0009_auto_20200323_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.CharField(default='100', max_length=100),
        ),
    ]
