# Generated by Django 2.2 on 2020-08-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_2', '0010_userprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='solo_status',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='x_solo',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='y_solo',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
